2020-03-26 15:10:38.756136: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-26 15:10:38.776548: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-03-26 15:10:44.575708: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-26 15:10:44.656299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:14:00.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2020-03-26 15:10:44.656465: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-26 15:10:44.656560: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-03-26 15:10:44.667369: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-03-26 15:10:44.670732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-03-26 15:10:44.686505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-03-26 15:10:44.690112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-03-26 15:10:44.690216: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-26 15:10:44.695445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-03-26 15:10:44.705685: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2693500000 Hz
2020-03-26 15:10:44.706105: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x62a4a20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-26 15:10:44.706181: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-26 15:10:44.816859: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x62a7580 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-26 15:10:44.817030: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2020-03-26 15:10:44.819671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:14:00.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2020-03-26 15:10:44.819760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-26 15:10:44.819825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-03-26 15:10:44.819901: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-03-26 15:10:44.819972: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-03-26 15:10:44.820041: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-03-26 15:10:44.820112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-03-26 15:10:44.820176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-26 15:10:44.825044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-03-26 15:10:44.825132: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-26 15:10:45.173398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-26 15:10:45.175035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-03-26 15:10:45.175107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-03-26 15:10:45.180671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10769 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:14:00.0, compute capability: 3.7)
2020-03-26 15:10:45.770686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-26 15:10:46.601529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Epoch 1 Batch 0 Loss 0.6347
Epoch 1 Batch 100 Loss 0.8774
Epoch 1 Batch 200 Loss 1.4572
Epoch 1 Batch 300 Loss 1.8394
Epoch 1 Batch 400 Loss 2.4924
Traceback (most recent call last):
  File "experiment.py", line 392, in <module>
    main()
  File "experiment.py", line 381, in main
    write_text(pred, 'Predictionnns')
  File "experiment.py", line 20, in write_text
    out_stream.write(sentence + "\n")
  File "/project/cq-training-1/project2/teams/team10/env/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 915, in binary_op_wrapper
    return func(x, y, name=name)
  File "/project/cq-training-1/project2/teams/team10/env/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1194, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "/project/cq-training-1/project2/teams/team10/env/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 480, in add_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/project/cq-training-1/project2/teams/team10/env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run AddV2: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0. [Op:AddV2] name: add/
